//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestType
    {
        public int Id { get; set; }
        public string Res_type { get; set; }
        public string Creation_dt { get; set; }
    }
}
